# XXX - would be nice to be able pipe these through formatters

from talon import Context

ctx = Context()
ctx.matches = r"""
language: de_DE
"""
abbreviations = {
    "anno" : "a.",
    "an" : "a.",
    "am" : "a.",
    "aus dem" : "a. d.",
    "aus der" : "a. d.",
    "Abbildung" : "Abb.",
    "abgekürzt" : "abgek.",
    "Abschnitt" : "Abschn.",
    "Abteilung" : "Abt.",
    "Abteilungen" : "Abt.",
    "Akademie" : "Akad.",
    "amerikanisch" : "amerikan.",
    "anatomisch" : "anatom.",
    "Anlage" : "Anl.",
    "Anmerkung" : "Anm.",
    "April" : "Apr.",
    "Arbeiter" : "Arb.",
    "Architektur" : "Archit.",
    "Auflage" : "Aufl.",
    "August" : "Aug.",
    "Ausgabe" : "Ausg.",
    "australisch" : "austr.",
    "aztekisch" : "aztek.",
    "Grad Baumé" : "° B.",
    "bearbeitet" : "bearb.",
    "Bearbeitung" : "Bearb.",
    "betreffend" : "betr.",
    "Bewohner" : "Bew.",
    "beziehungsweise" : "bez.",
    "Bezirk" : "Bez.",
    "Billion" : "Bill.",
    "böhmisch" : "böhm.",
    "Breite" : "Br.",
    "Grad Celsius" : "° C.",
    "circa" : "ca.",
    "Kubikmeter" : "cbm",
    "Kubikzentimeter" : "ccm",
    "Centime" : "Cent.",
    "chemisch" : "chem.",
    "chirurgisch" : "chirurg.",
    "Zentigramm" : "cg",
    "Kubikkilometer" : "ckm",
    "Centimeter" : "cm",
    "die Große" : "d. Gr.",
    "der Große" : "d. Gr.",
    "das heißt" : "d. h.",
    "des Jahres" : "d. J.",
    "der jüngere" : "d. jüng.",
    "des Monats" : "d. M.",
    "Departement" : "Depart.",
    "dergleichen" : "dergl.",
    "Derselbe" : "Ders.",
    "desgleichen" : "desgl.",
    "Dezember" : "Dez.",
    "dergleichen" : "dgl.",
    "Division" : "Div.",
    "dito" : "do.",
    "Dollar" : "Doll.",
    "Doktor" : "Dr.",
    "ehemalig" : "ehemal.",
    "einschließlich" : "einschl.",
    "Einwohner" : "Einw.",
    "englisch" : "engl.",
    "et cetera" : "etc.",
    "europäisch" : "europ.",
    "evangelisch" : "evang.",
    "eventuell" : "event.",
    "exklusive" : "exkl.",
    "folgende" : "f.",
    "Grad Fahrenheit" : "° F.",
    "Februar" : "Feb.",
    "mehrere folgende" : "ff.",
    "Figur" : "Fig.",
    "folgend" : "folg.",
    "fortgesetzt" : "fortges.",
    "Frankreich" : "Frankr.",
    "französisch" : "fr.",
    "französisch" : "frz.",
    "Gramm" : "g",
    "geboren" : "geb.",
    "gegründet" : "gegr.",
    "gemäß" : "gem.",
    "Gemeinde" : "Gem.",
    "genannt" : "gen.",
    "geographisch" : "geogr.",
    "geometrisch" : "geometr.",
    "Gesetz" : "Ges.",
    "Geschichte" : "Gesch.",
    "gestorben" : "gest.",
    "Gewicht" : "Gew.",
    "Glückstadt" : "Glückst.",
    "Grammatici" : "Gramm.",
    "griechisch" : "griech.",
    "Hamburg" : "Hamb.",
    "hochdeutsch" : "hochd.",
    "Holstein" : "Holst.",
    "herausgegeben" : "hrsg.",
    "im" : "i.",
    "illustriert" : "illustr.",
    "indisch" : "ind.",
    "inklusive" : "inkl.",
    "italienisch" : "it.",
    "Jahr" : "J.",
    "Jahrgang" : "Jahrg.",
    "Jahrhundert" : "Jahrh.",
    "jährlich" : "jährl.",
    "Januar" : "Jan.",
    "japanisch" : "japan.",
    "junior" : "jr.",
    "Kapitel" : "Kap.",
    "Kubikmeter" : "Kbkm.",
    "Kilogramm" : "kg",
    "königlich" : "kgl.",
    "Kilometer" : "km",
    "kritisch" : "krit.",
    "Liter" : "L.",
    "Länge" : "L.",
    "lateinisch" : "lat.",
    "löslich" : "lösl.",
    "Meter" : "m",
    "mechanisch" : "mechan.",
    "medizinisch" : "med.",
    "metrisch" : "metr.",
    "militärisch" : "militär.",
    "Million" : "Mill.",
    "Millionen" : "Mill.",
    "Minute" : "Min.",
    "Mitglieder" : "Mitgl.",
    "Mark" : "Mk.",
    "Mademoiselle" : "Mlle.",
    "Millimeter" : "mm",
    "Molekülmenge" : "Mol.",
    "musikalisch" : "musikal.",
    "Norden" : "N.",
    "nach Christi Geburt" : "n. Chr.",
    "nach dem" : "n. d.",
    "natürlich" : "natürl.",
    "naturwissenschaftlich" : "naturwissenschaftl.",
    "Neapel" : "Neap.",
    "Nikolaus" : "Nikol.",
    "Nordosten" : "NO.",
    "nordisch" : "nord.",
    "nordamerikanisch" : "nordamerikan.",
    "nordfriesisch" : "nordfries.",
    "nördlich" : "nördl.",
    "November" : "Nov.",
    "Nummer" : "Nr.",
    "Nordwesten" : "NW.",
    "Osten" : "O.",
    "ohne Jahresangabe" : "o. J.",
    "ohne Ortsangabe" : "o. O.",
    "oder" : "od.",
    "Oktober" : "Okt.",
    "Oxford" : "Oxf.",
    "Pfund" : "Pfd.",
    "physikalisch" : "physikal.",
    "physiologisch" : "physiol.",
    "plattdeutsch" : "plattd.",
    "Plural" : "Plur.",
    "Professor" : "Prof.",
    "Provinz" : "Prov.",
    "Quadratzentimeter" : "qcm",
    "Quadratkilometer" : "qkm",
    "Quadratmeter" : "qm",
    "Quadratmillimeter" : "qmm",
    "Grad Réaumur" : "° R.",
    "respektive" : "resp.",
    "rhetorisch" : "rhetor.",
    "siehe" : "s.",
    "Seite" : "S.",
    "Süden" : "S.",
    "siehe dort" : "s. d.",
    "siehe unter" : "s. u.",
    "so viel wie" : "s. v. w.",
    "Summa" : "Sa.",
    "Seine" : "Se.",
    "Sekunde" : "Sek.",
    "senior" : "sen.",
    "September" : "Sept.",
    "Silbergroschen" : "Sgr.",
    "skandinavisch" : "skandinav.",
    "Südosten" : "SO.",
    "sogenannt" : "sog., sogen.",
    "speziell" : "sp.",
    "spezifisch" : "sp.",
    "spanisch" : "span.",
    "spezifisches Gewicht" : "spez. Gew.",
    "Seiner" : "Sr.",
    "Sankt" : "St.",
    "Stunde" : "Std.",
    "südamerikanisch" : "südamerikan.",
    "südlich" : "südl.",
    "süddeutsch" : "südd.",
    "Südwesten" : "SW.",
    "Titel" : "Tit.",
    "Tonne" : "Ton.",
    "türkisch" : "türk.",
    "und" : "u.",
    "unter" : "u.",
    "und anderes" : "u. a.",
    "und anderes" : "u. a. m.",
    "andere Orte" : "u. a. O.",
    "und dergleichen" : "u. dgl.",
    "und dergleichen mehr" : "u. dgl. m.",
    "unter dem Titel" : "u. d. T.",
    "und öfter" : "u. ö.",
    "und so fort" : "u. s. f.",
    "und so weiter" : "u. s. w.",
    "ursprünglich" : "ursprngl.",
    "vom" : "v.",
    "vor" : "v.",
    "vor Christi Geburt" : "v. Chr.",
    "von der" : "v. d.",
    "von dem" : "v. d.",
    "vergrößert" : "vergr.",
    "vermehrt" : "verm.",
    "vergleiche" : "vgl.",
    "westlich" : "westl.",
    "weiblich" : "weibl.",
    "zum Beispiel" : "z. B.",
    "zur Disposition" : "z. D.",
    "Zeitschrift" : "Zeitschr.",
    "Ziffer" : "Ziff.",
}


ctx.lists["user.abbreviation"] = abbreviations
